import {useEffect,useState} from 'react';
import {Button} from '../../../../packages/ui/src';
import {AdminNotice,ReviewStatus} from '../../../../packages/ui/src/AdminStatus';
import {adminRequest as api} from './operations-api';
interface Person {id:string;masked_json:string;message:string;created_at:number;status:string;vote_id:string|null}
interface Page {entries:Person[];page:number;pageSize:number;total:number;columns?:string[]}
const date=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'});
export function ParticipantTable({base,onReveal,onDelete,busy,refreshKey}:{base:string;onReveal:(id:string)=>void;onDelete:(id:string)=>void;busy:boolean;refreshKey:string}){
 const names:Record<string,string>={name:'이름',phone:'연락처',email:'이메일',instagram:'인스타그램'};
 const [kind,setKind]=useState<'submission'|'voting'>('submission'),[drawCount,setDrawCount]=useState(1),[drawing,setDrawing]=useState(false),[winners,setWinners]=useState<Person[]>([]);
 const [data,setData]=useState<Page|null>(null),[page,setPage]=useState(1),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(refreshKey)return;let active=true;setLoading(true);api<Page>(base+'/participant-page?page='+page+'&kind='+kind).then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[base,page,refreshKey,kind]);
 const columns=data?.columns??Object.keys(names).filter(key=>data?.entries.some(p=>!!JSON.parse(p.masked_json)[key]));
 async function draw(){setDrawing(true);setError('');try{const result=await api<{entries:Person[]}>(base+'/draw-participants','POST',{kind,count:drawCount});setWinners(result.entries);}catch(e){setError(e instanceof Error?e.message:'추첨하지 못했습니다.');}finally{setDrawing(false);}}
 return <section><h2>개인정보</h2><div className="participant-tabs" role="tablist" aria-label="참여 구분">{(['submission','voting'] as const).map(value=><Button key={value} role="tab" disabled={drawing} aria-selected={kind===value} onClick={()=>{setKind(value);setData(null);setError('');setPage(1);setWinners([]);}}>{value==='submission'?'공모자':'투표자'}</Button>)}</div>
{error&&<AdminNotice tone="error">{error}</AdminNotice>}<p>{loading?'불러오는 중…':`총 ${data?.total??0}건 · 한국 시간`}</p><div className="admin-table-scroll"><table className="admin-data-table"><thead><tr><th>참여</th><th>문구</th><th>접수일시</th><th>상태</th>{columns.map(key=><th key={key}>{names[key]}</th>)}<th>관리</th></tr></thead><tbody>{data?.entries.map(person=>{const masked=JSON.parse(person.masked_json);return <tr key={person.id}><td>{person.vote_id?'투표':'공모'}</td><td className="entry-message">{person.message}</td><td>{date.format(person.created_at)}</td><td>{person.status==='vote'?'투표 완료':<ReviewStatus status={person.status}/>}</td>{columns.map(key=><td key={key}>{masked[key]||'—'}</td>)}<td><Button disabled={busy} onClick={()=>onReveal(person.id)}>원문 보기</Button><Button disabled={busy} onClick={()=>onDelete(person.id)}>개인정보 삭제</Button></td></tr>;})}{!loading&&!data?.entries.length&&<tr><td colSpan={5+columns.length}>참여 정보가 없습니다.</td></tr>}</tbody></table></div><div className="review-pagination"><Button disabled={busy||loading||!data||data.page<=1} onClick={()=>setPage(data!.page-1)}>이전</Button><span>{data?.page??1} / {Math.max(1,Math.ceil((data?.total??0)/50))} 페이지</span><Button disabled={busy||loading||!data||data.page*50>=data.total} onClick={()=>setPage(data!.page+1)}>다음</Button></div> <div className="participant-draw"><h3>랜덤 추첨</h3><p>현재 {kind==='submission'?'공모자':'투표자'} 전체에서 무작위로 뽑습니다. 이력은 저장하지 않으며 다시 추첨하면 같은 참여자가 나올 수 있습니다.</p><div className="row"><label>추첨 인원<input type="number" min={1} max={Math.min(100,data?.total??100)} value={drawCount} onChange={e=>setDrawCount(Number(e.target.value))}/></label><Button disabled={drawing||loading||!data?.total||!Number.isInteger(drawCount)||drawCount<1||drawCount>100||drawCount>data.total} onClick={draw}>{drawing?'추첨 중':'랜덤 추첨'}</Button></div>{!!winners.length&&<div aria-live="polite"><h4>이번 추첨 결과</h4><ol>{winners.map(person=>{const info=JSON.parse(person.masked_json);return <li key={person.id}><span>{Object.entries(info).filter(([,v])=>!!v).map(([k,v])=>`${names[k]??k}: ${v}`).join(' · ')}</span><Button onClick={()=>onReveal(person.id)}>원문 보기</Button></li>;})}</ol></div>}</div></section>;
}
