import {useRef,useState} from 'react';
import {BulletTextarea} from './BulletTextarea';
import {applyMark,rebaseMarks,type BodySize,type TextMark} from '../../../../packages/event-builder/src/rich-text';
export function RichTextEditor({label,value,marks=[],size='body',bullets=false,onChange}:{label:string;value:string;marks?:TextMark[];size?:BodySize;bullets?:boolean;onChange:(value:string,marks:TextMark[],size:BodySize)=>void}){
 const selection=useRef<[number,number]>([0,0]),[selected,setSelected]=useState(false);
 const apply=(style:Omit<TextMark,'start'|'end'>)=>{const [start,end]=selection.current;if(end>start)onChange(value,applyMark(marks,start,end,style),size);};
 const props={className:'body-editor','aria-label':label,value,onSelect:(e:{currentTarget:HTMLTextAreaElement})=>{selection.current=[e.currentTarget.selectionStart,e.currentTarget.selectionEnd];setSelected(selection.current[1]>selection.current[0]);}};
 const edit=(text:string)=>onChange(text,rebaseMarks(value,text,marks),size);
 return <div className="rich-editor"><label className="field">본문 전체 크기<select aria-label={`${label} 전체 크기`} value={size} onChange={e=>onChange(value,marks,e.target.value as BodySize)}><option value="small">작게 · 유의사항 크기</option><option value="body">기본 본문</option><option value="large">크게</option></select></label><div className="rich-toolbar" aria-label={`${label} 선택 글자 서식`}><select aria-label="선택 글자 크기" disabled={!selected} value="" onChange={e=>apply({size:e.target.value as BodySize})}><option value="">선택 글자 크기</option><option value="small">작게</option><option value="body">기본</option><option value="large">크게</option></select>{[['굵게',{bold:true}],['기울임',{italic:true}],['밑줄',{underline:true}],['강조',{tone:'emphasis'}],['회색',{tone:'default'}],['서식 지우기',{}]].map(([name,style])=><button type="button" key={String(name)} disabled={!selected} onMouseDown={e=>e.preventDefault()} onClick={()=>apply(style as Omit<TextMark,'start'|'end'>)}>{String(name)}</button>)}</div><label className="field">{label}{bullets?<BulletTextarea {...props} onValueChange={edit}/>:<textarea {...props} onChange={e=>edit(e.target.value)}/>}</label><small>글자를 선택한 뒤 서식을 적용하세요.{bullets?' 한 줄에 한 항목 · Tab 들여쓰기 / Shift+Tab 내어쓰기.':''}</small></div>;
}
