import {chromium} from 'playwright';import {firstSeat} from '../../artifacts/platform/model.mjs';import assert from 'node:assert/strict';
const base='http://127.0.0.1:8791/api/admin/events',headers={origin:'http://127.0.0.1:5190','content-type':'application/json'};
const draft=structuredClone(firstSeat);draft.privacyPolicy='';draft.slug='publish-ui-'+Date.now();draft.title='공개 흐름 검증';for(const stage of ['submission','voting'])draft.pages[stage].find(m=>m.type==='consent').consents=[{id:'privacy',label:'개인정보 동의',body:'단계별 개인정보 동의 원문'},...(stage==='submission'?[{id:'work-license',label:'응모작 활용 동의',body:'응모작 활용 동의 원문'}]:[])];
const r=await fetch(base,{method:'POST',headers,body:JSON.stringify(draft)});const event=await r.json();assert.ok(r.ok);
const b=await chromium.launch({channel:'chrome'});try{const p=await b.newPage({viewport:{width:1440,height:1000}});const requests=[];p.on('request',r=>{if(r.url().includes('/api/admin/'))requests.push(r.url());});await p.route('**/api/admin/events',async route=>{const response=await route.fetch();await route.fulfill({response,json:(await response.json()).filter(x=>x.id===event.id)});});await p.goto('http://127.0.0.1:5190/admin');await p.locator('.nav-event-title').waitFor();assert.equal(requests.filter(url=>url.endsWith('/policies')).length,0);
await p.getByRole('button',{name:'콘텐츠 편집',exact:true}).click();await p.getByRole('heading',{name:'푸터 설정',exact:true}).waitFor();assert.equal(await p.locator('details.stage-configuration').count(),0);await p.getByLabel('개인정보 처리방침',{exact:true}).fill('로컬 테스트용 개인정보 처리방침');await p.getByLabel('문의 주소',{exact:true}).fill('test@example.invalid');await p.getByRole('button',{name:'저장 후 공개',exact:true}).click();await p.getByText('페이지와 동의문을 공개했습니다.',{exact:true}).waitFor();const row=await(await fetch(base+'/'+event.id,{headers})).json();assert.equal(row.visibility,'published');const policies=await(await fetch(base+'/'+event.id+'/policies',{headers})).json();assert.equal(policies.length,3);await p.addStyleTag({content:'.toast{display:none!important}'});await p.screenshot({path:'artifacts/restructure/editor-settings.png'});
await p.locator('.admin-sidebar').getByRole('button',{name:'운영',exact:true}).click();await p.locator('.transition-checks li').first().waitFor();assert.equal(await p.getByText('페이지 공개 준비',{exact:true}).count(),0);await p.getByLabel('전환할 단계',{exact:true}).selectOption('submission');await p.locator('.transition-checks .is-complete').filter({hasText:'응모작 활용 동의문'}).waitFor();await p.getByRole('button',{name:'단계 전환',exact:true}).click();await p.getByRole('button',{name:'확인 후 전환',exact:true}).click();await p.getByRole('button',{name:'접수·투표 중지',exact:true}).waitFor();await p.locator('.transition-checks .is-complete').filter({hasText:'개인정보 동의문'}).waitFor();await p.screenshot({path:'artifacts/restructure/stage-overview-desktop.png'});await p.setViewportSize({width:390,height:844});await p.locator('.operations-panel h1').evaluate(el=>el.scrollIntoView({block:'start'}));await p.screenshot({path:'artifacts/restructure/stage-overview-mobile.png'});assert.equal((await(await fetch(base+'/'+event.id+'/policies',{headers})).json()).length,3);
await p.getByRole('button',{name:'접수·투표 중지',exact:true}).click();await p.getByText('공개 · 참여 중지',{exact:true}).waitFor();
console.log('Editor sections, one publish for all consent versions, no startup policy fanout, persistent readiness checklist and transition verified.');}finally{await b.close();const row=await(await fetch(base+'/'+event.id,{headers})).json();await fetch(base+'/'+event.id+'/archive',{method:'POST',headers,body:JSON.stringify({revision:row.revision})});}
