import {it,expect} from 'vitest';
import {deflateRawSync} from 'node:zlib';
import {parseFollowerArchives} from '../../packages/domain/src/follower-archive';
function crc32(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(entries:Record<string,string>,corrupt=false){let offset=0;const locals:Buffer[]=[],central:Buffer[]=[];for(const [path,text] of Object.entries(entries)){const name=Buffer.from(path),data=Buffer.from(text),compressed=deflateRawSync(data),crc=crc32(data)+(corrupt?1:0);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(8,8);local.writeUInt32LE(crc>>>0,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(name.length,26);locals.push(local,name,compressed);const header=Buffer.alloc(46);header.writeUInt32LE(0x02014b50);header.writeUInt16LE(8,10);header.writeUInt32LE(crc>>>0,16);header.writeUInt32LE(compressed.length,20);header.writeUInt32LE(data.length,24);header.writeUInt16LE(name.length,28);header.writeUInt32LE(offset,42);central.push(header,name);offset+=30+name.length+compressed.length;}const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(entries).length,10);end.writeUInt32LE(Buffer.concat(central).length,12);end.writeUInt32LE(offset,16);return new File([Buffer.concat([...locals,...central,end])],'instagram-example-2026-09-30-code.zip');}
const entry=(name:string)=>JSON.stringify([{string_list_data:[{value:name,href:'https://www.instagram.com/'+name,timestamp:1}]}]);
it('finds split lists anywhere in ZIP; excludes following; normalizes and deduplicates',async()=>{const result=await parseFollowerArchives([zip({'connections/followers_and_following/followers_1.json':entry('@Example_One'),'connections/followers_and_following/followers_2.json':entry('example_one'),'following.json':entry('not_a_follower')})]);expect(result.usernames).toEqual(['example_one']);expect(result.parts).toBe(2);expect(result.exportDate).toBe('2026-09-30');});
it('supports empty followers and title variant without assuming timestamp is export time',async()=>{expect((await parseFollowerArchives([zip({'followers_1.json':'[]'})])).usernames).toEqual([]);expect((await parseFollowerArchives([zip({'followers_1.json':'[{"title":"example","string_list_data":[{"href":"url","timestamp":1}]}]'})])).usernames).toEqual(['example']);});
it('rejects corrupt CRC, missing followers and invalid usernames',async()=>{await expect(parseFollowerArchives([zip({'followers_1.json':entry('example')},true)])).rejects.toThrow('손상');await expect(parseFollowerArchives([zip({'following.json':'{}'})])).rejects.toThrow('팔로워 JSON');await expect(parseFollowerArchives([zip({'followers_1.json':entry('<script>')})])).rejects.toThrow('계정명');});
it('falls back rather than inventing a date for renamed archives',async()=>{const source=zip({'followers_1.json':entry('example')});const result=await parseFollowerArchives([new File([await source.arrayBuffer()],'renamed.zip')]);expect(result.exportDate).toBeNull();});
