import {it,expect,vi,afterEach} from 'vitest';
import {pageMetadata,handlePage} from '../../packages/relay/src/page';
const env={PUBLIC_ORIGIN:'https://events.example.com',GOOGLE_CLIENT_ID:'',GOOGLE_CLIENT_SECRET:'',SESSION_SECRET:'session',GATEWAY_SECRET:'secret',ADMIN_WORKER_URL:'https://admin.example.com',PUBLIC_WORKER_URL:'https://public.example.com'};
const shell='<html><head><title>서울아레나 Events</title></head><body><script src="/assets/app.js"></script></body></html>';
afterEach(()=>vi.unstubAllGlobals());
it('escapes metadata and preserves application scripts',()=>{const html=pageMetadata(shell,'이벤트 "<제목>"','설명 & 내용','https://events.example.com/test');expect(html).toContain('<title>이벤트 &quot;&lt;제목&gt;&quot;</title>');expect(html).toContain('property="og:title"');expect(html).toContain('/assets/app.js');});
it('serves saved titles to crawlers without executing JavaScript',async()=>{vi.stubGlobal('fetch',vi.fn(async(input:Request|string|URL)=>String(input instanceof Request?input.url:input).includes('/app.html')?new Response(shell):Response.json({event:{title:'FIRST SEAT',browserTitle:'서울아레나 특별 이벤트',description:'참여 안내'}})));const response=await handlePage(new Request('https://events.example.com/first-seat'),env,shell);expect(response.status).toBe(200);expect(await response.text()).toContain('property="og:title" content="서울아레나 특별 이벤트"');});
it('never renders private or deleted events',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(null,{status:404})));const response=await handlePage(new Request('https://events.example.com/hidden'),env,shell);expect(response.status).toBe(404);expect(await response.text()).not.toContain('og:title');});
it('uses the admin title without requesting event data',async()=>{const fetcher=vi.fn(async()=>new Response(shell));vi.stubGlobal('fetch',fetcher);const response=await handlePage(new Request('https://events.example.com/admin'),env,shell);expect(await response.text()).toContain('<title>서울아레나 이벤트 백오피스</title>');expect(fetcher).not.toHaveBeenCalled();});
