import {readFileSync} from 'node:fs';
import {it,expect,beforeEach,afterEach} from 'vitest';
import {memoryD1} from '../platform/sqlite-d1';
import {EventsRepository} from '../../workers/data/src/events/repository';
import {firstSeat} from '../../packages/event-builder/src/model';
let memory:ReturnType<typeof memoryD1>,repo:EventsRepository;
beforeEach(()=>{memory=memoryD1(['0001_platform.sql','0002_assets.sql','0005_review_comments.sql'].map(f=>readFileSync('migrations/events/'+f,'utf8')).join('\n'));memory.sqlite.exec("INSERT INTO platform_admins VALUES('a','a','a@seoularena.net',1,0)");repo=new EventsRepository(memory.db,'a');});
afterEach(()=>memory.sqlite.close());
async function seed(){const event=await repo.create({...firstSeat,slug:'draw-test'});memory.sqlite.prepare("UPDATE events SET visibility='published' WHERE id=?").run(event.id);memory.sqlite.prepare("UPDATE event_stages SET accepting=1 WHERE event_id=? AND id='submission'").run(event.id);for(let i=0;i<55;i++){memory.sqlite.prepare("INSERT INTO event_entries(event_id,id,stage_id,round,message,created_at) VALUES(?,?,'submission',1,'test',0)").run(event.id,'e'+i);memory.sqlite.prepare("INSERT INTO event_participants VALUES(?,?,?,NULL,'{}','test','{\"email\":\"t***@test.invalid\"}',0)").run(event.id,'p'+i,'e'+i);}return event;}
it('saves comments independently from review status and rejects stale or oversized writes',async()=>{const e=await seed();await repo.comment(e.id,'e0','검토 의견',0);await repo.review(e.id,'e0','approved',1);await expect(repo.comment(e.id,'e0','stale',0)).rejects.toThrow();await expect(repo.comment(e.id,'e0','x'.repeat(301),1)).rejects.toThrow();const row=memory.sqlite.prepare('SELECT * FROM event_entries WHERE event_id=? AND id=?').get(e.id,'e0')!;expect(row.review_comment).toBe('검토 의견');expect(row.status).toBe('approved');expect(row.revision).toBe(2);});
it('draws from the full filtered pool without duplicates in one run or persisted history',async()=>{const e=await seed();const before=memory.sqlite.prepare('SELECT activity_revision FROM events WHERE id=?').get(e.id);const result=await repo.drawParticipants(e.id,'submission',55);expect(result.total).toBe(55);expect(new Set(result.entries.map(p=>p.id)).size).toBe(55);expect((await repo.drawParticipants(e.id,'submission',55)).entries).toHaveLength(55);expect(memory.sqlite.prepare('SELECT activity_revision FROM events WHERE id=?').get(e.id)).toEqual(before);await expect(repo.drawParticipants(e.id,'voting',1)).rejects.toThrow();await expect(repo.drawParticipants(e.id,'submission',56)).rejects.toThrow();await expect(repo.drawParticipants(e.id,'all',1)).rejects.toThrow();expect(await repo.participantPage(e.id,1,'voting')).toMatchObject({total:0,columns:[]});expect(await repo.participantPage(e.id,1,'submission')).toMatchObject({total:55,columns:['email']});});
